apiVersion: serving.knative.dev/v1 
kind: Service 
metadata:
  name: demo-service
  namespace: service-demo
spec:
  template:
    spec:
      containers:
        - image:  quay.io/monishkumar/microservice-app
          ports:
            - containerPort: 8080 
          env: 
            - name: MY_VAR
              value: "12345"
